# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 11:39
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20190313_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
